### ISSUE TITLE
GROUPBY missing form Excel Labs/AFE?

### ISSUE THREAD

**Issue by 0scarius** [microsoft/Excel-Labs#28]
Today was trying to refactor the multiple usage of a dynamic array formula using GROUPBY() into a dynamic function in the Excel Labs/AFE environment. However, the parser does not seem to recognize the GROUPBY statement. Is this not yet implemented in AFE?
![image](https://github.com/microsoft/Excel-Labs/assets/7230152/fad07e30-aacb-44f6-b9ed-e94631aca20b)

**Comment by NWilson** [comment]
@0scarius Thank you for reporting this. These functions are not yet implemented in AFE, which has not had a release since the announcement of these functions.

We do not have any timeline for adding support for these functions to the AFE debugger; however we will provide correct syntax highlighting for these in a future release of AFE.

**Comment by 0scarius** [comment]
Hi Nicholas,

Thanks for the reply. Addition to the debugger would not be my priority However, adding the functions to the AFE with correct syntax highlighting would be highly appreciated, as at this point, the syntax highlighter marks these functions as errors in my modules, meaning I can't save the code in that form. As a result, I have to build the code outside the AFE, which I find not desirable. Hoping for an expedient fix.

**Comment by NWilson** [comment]
@0scarius We will do a release shortly with this fix. However, I wouldn't expect that the (incorrect) red squiggly underline prevents saving correctly.

I have just typed in your formula from the screenshot above, into the Modules tab, using the current release version of AFE in the store. It saves correctly.

I did have to guess what the characters were under the "Unknown identifier" popup. It looks like you have a LET variable called "source" and a LAMBDA variable called "source", which looks suspicious.

**Comment by NWilson** [comment]
The fix has been released.

I would welcome further details though @0scarius if you do have a formula which is valid, but can't be saved by Excel Labs (even with red squigglies, which are purely visual and don't block saving).

**Comment by 0scarius** [comment]
Hi Nicholas,

 

Thanks for the heads up. I currently have v1.3, although I see that v1.4 is already available and I already ma on the bet-channel. I have tried to uninstall v1.3 and then re-install from the add-in store, but then 1.3 installs again. How can I get ahold of this new release?



 

Kind regards,

Oscar

**Comment by 0scarius** [comment]
When I have the new release installed, I will see if my problem persists and get back to you.

 

KR. Oscar

**Comment by NWilson** [comment]
> Thanks for the heads up. I currently have v1.3, although I see that v1.4 is already available and I already ma on the bet-channel. I have tried to uninstall v1.3 and then re-install from the add-in store, but then 1.3 installs again. How can I get ahold of this new release?

@0scarius That's an unusual problem, the latest update is normally available to everyone immediately, independent of Excel's own release channel.

I'm sorry this has been a problem for you.

Two thoughts:
* Test for version 1.4 in a fresh workbook
* Try clearing the web add-ins cache. This is bit complicated... File → Options → Trust Center (bottom left) → Trust Center Settings, then in the new dialog, Trusted Add-in catalogs → "Next time Office starts, clear all previously-started web add-ins cache". This is documented (a little bit) [here](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)

**Comment by 0scarius** [comment]
Hi Nicholas,

 

I went through the steps as you provided. However, unfortunately I still have/get v1.3 installed, also after following the steps from the link.

Any other thoughts on getting the latest release? 

 

 

KR. Oscar

**Comment by NWilson** [comment]
@0scarius 

Oh dear, I'm sorry it is still isn't working. I'm really guessing now, I don't have a strong idea.

You can remove and re-add an add-in using this Excel dialog:

<img width="533" alt="image" src="https://github.com/microsoft/Excel-Labs/assets/363415/a2230b23-abdd-4b9e-a8e2-83119623e3ba">

---

Secondly, we can verify which version of the Store manifest your version of Excel is using.

If you right-click on the Excel Labs taskpane, you should be able to select the "Inspect" option

<img width="410" alt="image" src="https://github.com/microsoft/Excel-Labs/assets/363415/323f983f-1bd1-422d-89ea-d79dbc38bd56">

In the titlebar of the Inspect window, you'll see the URL that's being loaded:

<img width="785" alt="image" src="https://github.com/microsoft/Excel-Labs/assets/363415/9fd2ce46-d4e6-4bb8-b9c1-1e7f25b0ad5b">

The current add-in's URL is https://advancedformulaenvironment.officeapps.live.com/taskpane.03.html.

If we see the _same_ URL in your version of Excel, then we have an issue with a stale cache for the taskpane resources. If we see a _different_ URL in your version of Excel, then we have an issue with a stale cache (or older version) of the Office Store app manifest. This experiment could narrow down the cause of the issue.
